---
# roles/tds/tasks/tds_instance_users.yml
# @version 2.02_2019-07-04
# @author Kevin Jeffery

- name: Creating TDS Instance Users
  user:
    name: "{{item.name}}"
    group: "{{item.group_name}}"
    home: "{{ item.home_directory | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    createhome: "{{ item.createhome | default(true) }}"
  with_items: "{{ tds_instances }}"
  loop_control:
    label: "{{item.name}}"
  when: tds_instances is defined
