all:
  hosts:
    localhost:
    datatier.sample.com:

  children:
    ansible:
      hosts:
        localhost:
    ldap:
      hosts:
        datatier.sample.com:
    isamldap-servers:
      hosts:
        datatier.sample.com:

  vars:
    useful_packages:
    - "open-vm-tools"
    - "bind-utils"
    - "unzip"
    - "net-tools"
    - "git"
    - "wget"
    - "nano"
    roles_path: "/ansible/roles"
