---
# inventory/sample.yml
# @version 1.05_2020-DEC-22
# @author Kevin Jeffery

all:
  hosts:
    localhost:
    datatier.sample.com:
      ansible_user: ansible
      ansible_ssh_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36333433663039353938383362336235636230383361383833356436666562383235616637303531
          3235326362623435363933623766303262373432313362380a363533613966626132353130356466
          36666134646666613531666334636335396165626234356139666234663661366261646462333431
          6163636461663637360a353766633534323763346665656432643334356134373335326533343661
          3438
      host_name: datatier.sample.com
      ip_address: "192.168.42.100"
      ip_gateway: "192.168.42.2"
      ip_netmask: "255.255.255.0"
    esxi.sample.com:
      ansible_user: root
      ansible_ssh_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36333433663039353938383362336235636230383361383833356436666562383235616637303531
          3235326362623435363933623766303262373432313362380a363533613966626132353130356466
          36666134646666613531666334636335396165626234356139666234663661366261646462333431
          6163636461663637360a353766633534323763346665656432643334356134373335326533343661
          3438
      vcenter_username: "{{ansible_user}}"
      vcenter_password: "{{ansible_ssh_pass}}"
      vcenter_datacenter: "ha-datacenter"
      vmware_folder: "/ha-datacenter/vm"
      vmware_iso_datastore: "datastore1"
      vmware_iso_path: "iso"
      centos7_list:
      - vm_name: datatier
        host_name: datatier.sample.com
        datastore: datastore1
        networks:
        - networkName: "VM Network"
          virtualDev: "vmxnet3"
        hdd_size: 40
      isamva_list:
      - vm_name: isamva1
        host_name: isamva1.sample.com
        datastore: datastore1
        networks:
        - networkName: "VM Network"
          virtualDev: "vmxnet3"
        hdd_size: 40
        ram_size: 4096
      - vm_name: isamva2
        host_name: isamva2.sample.com
        datastore: datastore1
        networks:
          virtualDev: "vmxnet3"
        hdd_size: 40
        ram_size: 4096
    isamva1.sample.com:
      host_name: "isamva1.sample.com"
      ip_address: "192.168.42.101"
      ip_gateway: "192.168.42.2"
      ip_netmask: "255.255.255.0"
    isamva2.sample.com:
      host_name: "isamva2.sample.com"
      ip_address: "192.168.42.201"
      ip_gateway: "192.168.42.2"
      ip_netmask: "255.255.255.0"
    dc1.sample.com:
      host_name: "dc1.sample.com"
      ip_address: "192.168.42.161"
    dc2.sample.com:
      host_name: "dc2.sample.com"
      ip_address: "192.168.42.162"
    win160.sample.com:
      host_name: "win160.sample.com"
      ip_address: "192.168.42.160"
  children:
    isamva:
      hosts:
        isamva1.sample.com:
        isamva2.sample.com:
    esxi:
      hosts:
        esxi.sample.com:
      vars:
        ansible_python_interpreter: "/bin/python"
        isamva_iso: "isam_9.0.4.0_20171201-2325.iso"
        centos7_iso: "CentOS-7-x86_64-Minimal-1810.iso"
    ansible:
      hosts:
        localhost:
      vars:
        useful_packages:
        - "open-vm-tools"
        - "bind-utils"
        - "unzip"
        - "net-tools"
        - "git"
        - "wget"
        - "nano"
    ldap:
      hosts:
        datatier.sample.com:
      vars:
        useful_packages:
        - "open-vm-tools"
        - "bind-utils"
        - "unzip"
        - "rsync"
        gskit_install_version: "8.0.55.4"
        gskit_install_suffix: "FP004"
        javasdk_install_version: "8.0.5.20"
        javasdk_install_suffix : "FP0020"
        db2_install_archive: "v11.1.4fp4_linuxx64_server_t.tar.gz"
        db2_install_version: "11.1.4.4"
        db2_install_packages:
        - pam
        - pam.i686
        - ksh
        db2_license_enabled: "true"
        db2_license_archive: "DB2_ESE_Restricted_Activation_11.1.zip"
        db2_highcapacity_enabled: "true"
        tds_install_fixpack_version: "6.4.0.18"
        tds_install_fixpack_suffix: "IF0018"
        tds_install_db2_version: "{{ db2_install_version }}"
    isamldap_servers:
      hosts:
        datatier.sample.com:
    msad:
      hosts:
        dc1.sample.com:
        dc2.sample.com:
        win2016.sample.com:
      vars:
        ansible_user: "ansible@SAMPLE.COM"
        ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36333433663039353938383362336235636230383361383833356436666562383235616637303531
          3235326362623435363933623766303262373432313362380a363533613966626132353130356466
          36666134646666613531666334636335396165626234356139666234663661366261646462333431
          6163636461663637360a353766633534323763346665656432643334356134373335326533343661
          3438
        ansible_connection: "winrm"
        ansible_port: 5985
        ansible_winrm_transport: "kerberos"
   vars:
    roles_path: "/ansible/roles"
    software_src_dir: "/ansible/software"
    software_dest_dir: "/appdata/software"
    db2_home: "/opt/ibm/DB2/v11.1"
    ldap_home: "/opt/ibm/ldap/V6.4"
    winrm_kerberos_config:
      domain: "sample.com"
      kdc:
      - "dc1.sample.com"
      - "dc2.sample.com"
