---
# roles/esxi/centos7_build/tasks/centos7_provision.yml
# @version v1.02_2019-DEC-07
# @author Kevin Jeffery

- name: Create the VM - {{item.vm_name}}
  vars:
    ansible_user: "{{ hostvars[vcenter_hostname]['vcenter_username'] }}"
    ansible_ssh_pass: "{{ hostvars[vcenter_hostname]['vcenter_password'] }}"
  esxi:
    action: "create"
    vm_name: "{{ item.vm_name }}"
    vm_datastore: "{{ item.datastore }}"
    vm_resource_pool: "{{ item.resource_pool | default(omit) }}"
    vm_guest_os: "{{ item.guest_os | default('centos7-64') }}"
    vm_mem_size: "{{ item.mem_size | default(4096) }}"
    vm_cpu_count: "{{ item.cpu_count | default(1) }}"
    vm_scsi_type: "lsilogic"
    vm_hdd_size: "{{ item.hdd_size | default(40) }}"
    vm_networks: "{{ item.networks }}"
    vm_iso_image: "/vmfs/volumes/{{ vmware_iso_datastore }}/{{ vmware_iso_path }}/{{ centos7_iso }}"
    vm_iso_image2: "/vmfs/volumes/{{ vmware_iso_datastore }}/{{ vmware_iso_path }}/{{ item.host_name }}.iso"
  register: vm_create
  delegate_to: "{{ vcenter_hostname }}"

- name: Start the VM - {{item.vm_name}}
  vars:
    ansible_user: "{{ hostvars[vcenter_hostname]['vcenter_username'] }}"
    ansible_ssh_pass: "{{ hostvars[vcenter_hostname]['vcenter_password'] }}"
  esxi:
    action: "poweron"
    vm_name: "{{ item.vm_name }}"
  when: vm_create.changed
  ansible_user: "{{ hostvars[vcenter_hostname]['vcenter_username'] }}"
  ansible_ssh_pass: "{{ hostvars[vcenter_hostname]['vcenter_password'] }}"
  delegate_to: "{{ vcenter_hostname }}"

- name: Wait for restart - {{item.vm_name}}
  wait_for:
    host: "{{ item.host_name }}"
    port: 22
    delay: 300
    sleep: 15
    timeout: 900
  when: vm_create.changed
  delegate_to: localhost

- name: Set authorized key from file - {{ item.host_name }}
  vars:
    ansible_user: "{{ hostvars[item.host_name]['ansible_user'] | default('ansible') }}"
    ansible_ssh_pass: "{{ hostvars[item.host_name]['ansible_ssh_pass'] }}"
  authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
  delegate_to: "{{ item.host_name }}"

- name: Adding hostname entry to /etc/hosts - {{ item.host_name }}
  vars:
    ansible_user: "{{ hostvars[item.host_name]['ansible_user'] | default('ansible') }}"
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item.host_name]['ip_address'] }} {{ item.host_name }}$"
    line: "{{ hostvars[item.host_name]['ip_address'] }} {{ item.host_name }}"
  delegate_to: "{{ item.host_name }}"

- name: Update the system - {{ item.host_name }}
  vars:
    ansible_user: "{{ hostvars[item.host_name]['ansible_user'] | default('ansible') }}"
  yum:
    name: "*"
    state: latest
  become: yes
  register: ret_out
  when: vm_create.changed
  delegate_to: "{{ item.host_name }}"

- name: Reboot the server - {{ item.host_name }}
  vars:
    ansible_user: "{{ hostvars[vcenter_hostname]['vcenter_username'] }}"
    ansible_ssh_pass: "{{ hostvars[vcenter_hostname]['vcenter_password'] }}"
  esxi:
    action: "reboot"
    vm_name: "{{ item.vm_name }}"
  when: ret_out.changed
  delegate_to: "{{ vcenter_hostname }}"
