---
# roles/esxi/centos7_build/tasks/centos7_template.yml
# @version v1.02_2019-DEC-07
# @author Kevin Jeffery

- name: CentOS7 Template **** {{ item.vm_name }}
  debug:
    var: item.host_name

- name: Create Kickstart directory
  file:
    path: "{{ inventory_dir }}/centos7/{{ item.vm_name }}/iso"
    state: "directory"
  delegate_to: localhost

- name: Template the Kickstart configuration file - {{ item.vm_name }}
  vars:
    KS_hostname: "{{ item.host_name }}"
    KS_ip_address: "{{ hostvars[item.host_name]['ip_address'] }}"
    KS_ip_netmask: "{{ hostvars[item.host_name]['ip_netmask'] }}"
    KS_ip_gateway: "{{ hostvars[item.host_name]['ip_gateway'] }}"
    KS_dns_server: "{{ hostvars[item.host_name]['dns_server'] | default(KS_ip_gateway) }}"
    KS_ansible_user: "{{ hostvars[item.host_name]['ansible_user'] }}"
    KS_ansible_password: "{{ hostvars[item.host_name]['ansible_ssh_pass'] }}"
    KS_ansible_group: "{{ hostvars[item.host_name]['ansible_user'] }}"
    KS_root_password: "{{ hostvars[item.host_name]['root_password'] | default(KS_ansible_password) }}"
  template:
    src: "../templates/ks.cfg.j2"
    dest: "{{ inventory_dir }}/centos7/{{ item.vm_name }}/iso/ks.cfg"
  delegate_to: localhost
  
- name: Create the Kickstart ISO - {{ item.vm_name }}
  command: "genisoimage -J -r -V OEMDRV -o {{ inventory_dir }}/centos7/{{ item.vm_name }}/{{ item.host_name }}.iso {{ inventory_dir }}/centos7/{{ item.vm_name }}/iso"
  args:
    creates: "{{ inventory_dir }}/centos7/{{ item.vm_name }}/{{ item.host_name }}.iso"
  delegate_to: localhost

- name: Check the Kickstart ISO image on {{ vcenter_hostname }}
  vsphere_file:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: "{{ vcenter_datacenter }}"
    datastore: "{{ vmware_iso_datastore }}"
    path: "{{ vmware_iso_path }}/{{ item.host_name }}.iso"
    state: "touch"
    validate_certs: no
  register: ret_iso
  delegate_to: localhost

- name: Deploy the Kickstart ISO to {{ vcenter_hostname }}
  vsphere_copy:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    src: "{{ inventory_dir }}/centos7/{{ item.vm_name }}/{{ item.host_name }}.iso"
    datacenter: "{{ vcenter_datacenter }}"
    datastore: "{{ vmware_iso_datastore }}"
    path: "{{ vmware_iso_path }}/{{ item.host_name }}.iso"
    validate_certs: no
  when: ret_iso.changed
  ignore_errors: true
  delegate_to: localhost
