---
# roles/isamldap/tasks/isamldap_instance_ldif.yml
# @version v2.01_2019-DEC-23
# @author Kevin Jeffery

# Set ISAM LDAP Instance SSL Configuration
- name: Deploy the SSL Keystore
  copy:
    src: "{{ ssl_keystore_path }}/{{ isamldap_keystore }}"
    dest: "{{ isamldap_instance_home }}/idsslapd-{{ isamldap_instance_name }}/etc/{{ isamldap_keystore }}"
    owner: "{{ isamldap_instance_name }}"
  become: "yes"
  when: ssl_keystore_path is defined and isamldap_keystore is defined

- name: Deploy the SSL Stash file
  copy: 
    src: "{{ ssl_keystore_path }}/{{ isamldap_keystash }}"
    dest: "{{ isamldap_instance_home }}/idsslapd-{{ isamldap_instance_name }}/etc/{{ isamldap_keystash }}"
    owner: "{{ isamldap_instance_name }}"
  become: "yes"
  when: ssl_keystore_path is defined and isamldap_keystash is defined

- name: Template the configuration LDIF
  template:
    src: "{{ isamldap_config_ldif }}"
    dest: "{{ isamldap_instance_home }}/isamldap_config.ldif"
    owner: "{{ isamldap_instance_name }}"
    group: "idsldap"
  become: "yes"
  register: config_file

- name: Update configuration
  command: "{{ ldap_home }}/bin/idsldapmodify -D {{ isamldap_admin_id }} -w {{ isamldap_admin_pwd }} -c -h {{ inventory_hostname }} -p {{ isamldap_port }} -f {{ isamldap_instance_home }}/isamldap_config.ldif"
  become: "yes"
  when: config_file.changed

# Configure Autostart for instance components
- name: Deploy IDSLDAP Service file
  template:
    src: "../templates/isamldap.service.j2"
    dest: "/etc/systemd/system/idsslapd-{{ isamldap_instance_name }}.service"
    force: yes
  become: "yes"
  register: debug_isamldap_service

- name: Deploy IDSLDAP Admin Service file
  template:
    src: "../templates/isamdiradmin.service.j2"
    dest: "/etc/systemd/system/ibmdiradm-{{ isamldap_instance_name }}.service"
    force: yes
  become: "yes"
  register: debug_isamdiradmin_service

- name: Stop the ISAM LDAP Admin instance
  tdsinstance: 
    instance: "{{ isamldap_instance_name }}"
    action: adminstop
  become: "yes"
  when: debug_isamdiradmin_service.changed

- name: Stop the ISAM LDAP instance
  tdsinstance: 
    instance: "{{ isamldap_instance_name }}"
    action: stop
  become: "yes"
  when: debug_isamldap_service.changed

#- name: Stop the ISAM LDAP DB2 instance
#  db2instance:
#    instance: "{{ isamldap_instance_name }}"
#    action: stop
#    force: True
#  become: True
#  become_user: "{{ isamldap_instance_name }}"
#  when: debug_isamldap_service.changed

- name: Enable ISAM LDAP Service
  service:
    name: "idsslapd-{{ isamldap_instance_name }}.service"
    enabled: yes
  become: "yes"

- name: Enable ISAM LDAP Admin Service
  service:
    name: "ibmdiradm-{{ isamldap_instance_name }}.service"
    enabled: yes
  become: "yes"

- name: Start ISAM LDAP Service
  service:
    name: "idsslapd-{{ isamldap_instance_name }}.service"
    state: started
  become: "yes"

- name: Start ISAM LDAP Admin Service
  service:
    name: "ibmdiradm-{{ isamldap_instance_name }}.service"
    state: started
  become: "yes"
