---
# roles/db2/defaults/main.yml
# @version 2.03_2019-07-03
# @author Kevin Jeffery 
# Response file keywords: https://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.qb.server.doc/doc/r0007505.html

# The following can be overridden with group or host variables
# db2_install_url: ""
db2_install_version: "10.5.0.9"
db2_install_archive: "v10.5fp9_linuxx64_server_t.tar.gz"
db2_install_creates: server_t
# Packages required for both DB2 v10.5 and DB2 v11.1
db2_install_packages:
  - pam
# Comment lines below for DB2 v11.1 or override with variables
  - libaio
  - compat-libstdc++-33.i686
  - compat-libstdc++-33
  - libstdc++
  - ksh
db2_install_file: "{{db2_home|default('/opt/ibm/DB2/V10.5')}}"
db2_install_components:
  - name: LDAP_EXPLOITATION
# Create the instances listed in 'db2_instances' variable.
db2_install_create_instances: false

# List of instances to be created
# NOTE: root installation is required
# db2_instances:
# Those five params are mandatory to create a DB2 instance
#  - instance: "DB2INST1"
#    name: "db2inst1"
#    group_name: "db2iadm1"
#    fenced_username: "db2fenc1"
#    fenced_group_name: "db2fadm1"

# Set to true if you have a DB2 license file
db2_license_enabled: "false"
db2_license_archive: "DB2_ESE_Restrict_QS_Act_10.5.0.8.zip"
db2_license_file: "ese_o/db2/license/db2ese_o.lic"
# Set to "true" for DB2 11.4 if you have the High Capacity license
db2_highcapacity_enabled: "false"
db2_highcapacity_archive: "DB2_OHC_Restricted_Activation_11.1.zip"
db2_highcapacity_file: "hc/db2/license/db2hc.lic"
#

db2_install:
  version: "{{db2_install_version}}"
  location: "{{software_src_dir | default('/ansible/software')}}"
  url: "{{db2_install_url | default(omit)}}"
  dest: "{{software_dest_dir | default('/appdata/software')}}"
  archive: "{{db2_install_archive}}"
  creates: "{{db2_install_creates}}"
  prod: "DB2_SERVER_EDITION"
  file: "{{db2_install_file}}"
  lic_agreement: "ACCEPT"
  install_type: "CUSTOM"
  components: "{{db2_install_components}}"
  create_instances: "{{db2_install_create_instances}}"
  global_params: "{{db2_install.global_params | default(omit)}}"

db2_license:
  enabled: "{{db2_license_enabled}}"
  location: "{{software_src_dir | default('/ansible/software')}}"
  dest: "{{software_dest_dir | default('/appdata/software')}}"
  archive: "{{db2_license_archive}}"
  file: "{{db2_license_file}}"

# DB2 High Capacity License - DB2 11.1 only
db2_highcapacity:
  enabled: "{{db2_highcapacity_enabled}}"
  location: "{{software_src_dir | default('/ansible/software')}}"
  dest: "{{software_dest_dir}} | default('/appdata/software')}}"
  archive: "{{db2_highcapacity_archive}}"
  file: "{{db2_highcapacity_file}}"
