-- cleanup_oauth20_token_extra_attribute.sql
-- v2.00_2020-08-29
-- Kevin Jeffery
-- Example: CALL CLEANUP_OAUTH20_TOKEN_EXTRA_ATTRIBUTE(1000000, ?, ?, ?)

CREATE OR REPLACE PROCEDURE CLEANUP_OAUTH20_TOKEN_EXTRA_ATTRIBUTE (
    IN maxCount INT,
    OUT rowCount INT,
    OUT expiredCount INT,
    OUT cleanupCount INT)
LANGUAGE SQL
MODIFIES SQL DATA
AUTONOMOUS
BEGIN

SELECT count(*) INTO rowCount FROM OAUTH20_TOKEN_EXTRA_ATTRIBUTE;
SELECT count(*) INTO expiredCount FROM OAUTH20_TOKEN_EXTRA_ATTRIBUTE
WHERE STATE_ID NOT IN (SELECT STATE_ID FROM OAUTH20_TOKEN_CACHE);
SET cleanupCount = 0;
IF expiredCount < maxCount THEN
    SET maxCount = expiredCount;
END IF;

L0: WHILE (cleanupCount < maxCount) DO
    L1: FOR expireID AS
    SELECT STATE_ID,ATTR_NAME
    FROM OAUTH20_TOKEN_EXTRA_ATTRIBUTE
    WHERE STATE_ID NOT IN (select STATE_ID FROM OAUTH20_TOKEN_CACHE) FETCH FIRST 1000 ROWS ONLY
    DO
        DELETE FROM OAUTH20_TOKEN_EXTRA_ATTRIBUTE WHERE STATE_ID = expireID.STATE_ID AND ATTR_NAME = expireID.ATTR_NAME;
        SET cleanupCount = cleanupCount + 1;
        IF cleanupCount >= maxCount THEN
            LEAVE L1;
        END IF;
    END FOR;
    COMMIT;
END WHILE;

END
