---
# roles/db2/tasks/get_db2.yml
# @version 2.04_2019-07-11
# @author Kevin Jeffery - kjeffery@ca.ibm.com
#Download a DB2 copy from a custom URL (Could be a http, an ftp whatever.)

- name: Download DB2 Binary
  get_url:
    url: "{{db2_install.url}}"
    dest: "{{db2_install.dest}}/{{db2_install.archive}}"
    headers: "{{db2_download_headers | default(omit)}}"
    validate_certs: "no"
  when: db2_install.url != ""

- name: Stage DB2 Binary
  copy:
    src: "{{db2_install.location}}/{{db2_install.archive}}"
    dest: "{{db2_install.dest}}/{{db2_install.archive}}"
  when: db2_install.url == ""

- name: Download DB2 License
  get_url:
    url: "{{db2_license.url}}"
    dest: "{{db2_license.dest}}/{{db2_license.archive}}"
    headers: "{{db2_download_headers | default(omit)}}"
  when: db2_license.enabled == "true" and db2_license.url != ""

- name: Stage DB2 License
  copy:
    src: "{{db2_license.location}}/{{db2_license.archive}}"
    dest: "{{db2_license.dest}}/{{db2_license.archive}}"
  when: db2_license.enabled == "true" and db2_license.url == ""

- name: Download DB2 High volume
  get_url:
    url: "{{db2_highcapacity.url}}"
    dest: "{{db2_highcapacity.dest}}/{{db2_highcapacity.archive}}"
    headers: "{{db2_download_headers | default(omit)}}"
  when: db2_highcapacity.enabled == "true" and db2_highcapacity.url != ""

- name: Stage DB2 High volume
  copy:
    src: "{{db2_highcapacity.location}}/{{db2_highcapacity.archive}}"
    dest: "{{db2_highcapacity.dest}}/{{db2_highcapacity.archive}}"
  when: db2_highcapacity.enabled == "true" and db2_highcapacity.url == ""

- name: Decompressing DB2 Server
  unarchive:
    src: "{{db2_install.dest}}/{{db2_install.archive}}"
    remote_src: "yes"
    dest: "{{db2_install.dest}}"
    creates: "{{db2_install.dest}}/{{db2_install.creates}}"

- name: Decompress DB2 License
  unarchive:
    src: "{{db2_license.dest}}/{{db2_license.archive}}"
    remote_src: "yes"
    dest: "{{db2_license.dest}}"
    creates: "{{db2_license.dest}}/{{db2_license.file}}"
  when: db2_license.enabled == "true"

- name: Decompress DB2 High Volume
  unarchive:
    src: "{{db2_highcapacity.dest}}/{{db2_highcapacity.archive}}"
    remote_src: "yes"
    dest: "{{db2_highcapacity.dest}}"
    creates: "{{db2_highcapacity.dest}}/{{db2_highcapacity.file}}"
  when: db2_highcapacity.enabled == "true"