---
# roles/db2/tasks/packages-redhat.yml
# @version 2.01_2019-06-30
# @author Kevin Jeffery
  - name: Installing DB2 pre requisites packages - RedHat
    yum: name="{{db2_packages}}" state=latest update_cache=yes disable_gpg_check=yes
