---
# roles/db2/tasks/packages-redhat.yml
# @version 2.02_2019-07-04
# @author Kevin Jeffery
  - name: Installing DB2 pre requisites packages - RedHat
    yum: name="{{db2_install.packages}}" state=latest update_cache=yes disable_gpg_check=yes
