---
# roles/gskit/tasks/main.yml
# @version v2.04_2019-07-11
# @author Kevin Jeffery

# Install the system GSKit
- name: Download the GSKit archive
  get_url:
    url: "{{gskit_install.url}}"
    dest: "{{gskit_install.dest}}/{{gskit_install.archive}}"
    headers: "{{gskit_download_headers | default(omit)}}"
    validate_certs: "no"
  when: gskit_install.url != ""

- name: Stage the GSKit archive
  copy:
    src: "{{gskit_install.location}}/{{gskit_install.archive}}"
    dest: "{{gskit_install.dest}}/{{gskit_install.archive}}"
  when: gskit_install.url == ""
  
- name: Decompressing GSKit Package
  unarchive:
    src: "{{gskit_install.dest}}/{{gskit_install.archive}}"
    dest: "{{gskit_install.dest}}"
    remote_src: yes
    creates: "{{gskit_install.dest}}/{{gskit_install.basename}}"

- name: Install 32 bit packages
  package:
    name: "{{gskit_install.dest}}/{{gskit_install.basename}}/32/{{item.name}}"
  with_items: "{{gskit_install.gskit32}}"
  loop_control:
    label: "{{item.name}}"

- name: Install 64 bit packages
  package:
    name: "{{gskit_install.dest}}/{{gskit_install.basename}}/64/{{item.name}}"
  with_items: "{{gskit_install.gskit64}}"
  loop_control:
    label: "{{item.name}}"

