---
# playbooks/esxi_isamva.yml
# @version v1.00_2019-NOV-07
# @author Kevin Jeffery

- name: ISAMVA Autoconfig **** {{item.vm_name}}
  debug:
    var: item.host_name

# Get the machine state.  Has to be stopped to proceed
- name: Get VM information
  vmware_guest:
    name: "{{item.vm_name}}"
    state: "present"
    hostname: "{{ inventory_hostname }}"
    esxi_hostname: "{{ inventory_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
  register: ret_guest
  delegate_to: localhost

- name: VM Info
  debug:
    var: ret_guest.instance.hw_power_status
    # verbosity: 3

- name: Swap CD to autoconfig
  lineinfile:
    path: "/vmfs/volumes/{{item.datastore}}/{{item.vm_name}}/{{item.vm_name}}.vmx"
    regexp: "^sata0:0.fileName = .*"
    line: "sata0:0.fileName = \"/vmfs/volumes/{{vmware_iso_datastore}}/{{vmware_iso_path}}/{{item.host_name}}.iso\""
  when: ret_guest.instance.hw_power_status == 'poweredOff'
  register: ret_swapcd

- name: Get the VMID for restart
  shell: "/bin/vim-cmd vmsvc/getallvms |grep {{item.vm_name}} |cut -f0 -d' '"
  register: ret_vmid
  when: ret_guest.instance.hw_power_status == 'poweredOff' and ret_swapcd.changed
  
- name: Restart VM if changed
  command: "/bin/vim-cmd vmsvc/power.on {{ret_vmid.stdout}}"
  when: ret_guest.instance.hw_power_status == 'poweredOff' and ret_swapcd.changed

# Check the CD ISO image